### PR TITLE
Add Non-Aggregated Depth Order Book

### PR DESCRIPTION
**Pull request by futuristly**
Can you please Add Non-Aggregated Depth Order Book for the Kucoin .Net wrapper?

Thanks.

### CODE REVIEW

**Comment by JKorf** [comment]
What subscription are you referring to? Also are you trying to merge something or is this just a request?

**Comment by futuristly** [comment]
This is just a request.
I need real time order book in depth (non-aggregated) meaning each price and amount is independent without the need for sum up

**Comment by JKorf** [comment]
Can you have a look at the API documentation and see what you're missing? I'm pretty sure all available streams in the API are implemented in this library.

**Comment by futuristly** [comment]
> Can you have a look at the API documentation and see what you're missing? I'm pretty sure all available streams in the API are implemented in this library.

image
This is on kucoin offical API, i only see aggregated order book update from your API..

**Pull request closed without merging**
