### PR TITLE
Introducing new GetAccountLedgers

### PR DESCRIPTION
**Pull request by Zebio21**
Tagged old function to obsolete
CReating new one with all optionals parameters
Adding Kucoin BizType enumeation and converters

### CODE REVIEW

**Comment by Zebio21** [comment]
Integration failed due to purposed updated version of CrypoExchange.net version

**Comment by JKorf** [comment]
Thanks for the PR. Could you also update the KucoinClient interface?

**Comment by Zebio21** [comment]
> Thanks for the PR. Could you also update the KucoinClient interface?

What do you mean ?
The KucoinClient interface is updated with obsolete and new functions

**Comment by JKorf** [comment]
Sorry, must've been sleeping. Thanks for contributing

**Pull request merged**
